<a href="https://colab.research.google.com/github/Lyeon1/study/blob/master/%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC_Numpy_%EA%B3%B5%EB%B6%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np

a=np.array([1,2,3])
print(a+3)
print(a.shape)
print()

b=np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b.shape)
print()

print(a.ndim)
print(b.ndim)
print()

c=[1,2,3]
print(type(c))
d=np.array(c)
print(type(d))
print(d, d.dtype)
print()

e=[1,2,3,'test']
f=np.array(e)
print(f,f.dtype)
print()

g=[1,2,3,4.0]
h=np.array(g)
print(h,h.dtype)
print()

i=np.array([1,2,3])
j=i.astype('float64')
print(j,j.dtype)
print()

k=i.astype('int32')
print(k,k.dtype)
print()

l=np.arange(10)
print(l)
print(l.dtype,l.shape)
print()

m=np.zeros((3,2),dtype="int32")
print(m, m.dtype, m.shape)
print()

n=np.ones((3,2))
print(n, n.dtype, n.shape)
print()

o=np.arange(10)
print('o: \n', o)
p=o.reshape(2,5)
print("p: \n", p)
print()

q=np.arange(8)
r=q.reshape(2,2,2)
print("r: \n", r)
print()

s=np.arange(start=1, stop=10)
print("s:",s)
t=s[2]
print("t:",t)


[4 5 6]
(3,)

<class 'numpy.ndarray'>
(2, 3)

1
2

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64

['1' '2' '3' 'test'] <U21

[1. 2. 3. 4.] float64

[1. 2. 3.] float64

[1 2 3] int32

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)

[[0 0]
 [0 0]
 [0 0]] int32 (3, 2)

[[1. 1.]
 [1. 1.]
 [1. 1.]] float64 (3, 2)

o: 
 [0 1 2 3 4 5 6 7 8 9]
p: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

r: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

s: [1 2 3 4 5 6 7 8 9]
t: 3


In [26]:
a=np.arange(start=1, stop=10)
b=a.reshape(3,3)
print(b)
print('(row=0, col=0) index를 가르키는 값:',b[0,0])
print('(row=0, col=1) index를 가르키는 값:',b[0,1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index를 가르키는 값: 1
(row=0, col=1) index를 가르키는 값: 2


In [58]:
a=np.arange(start=1, stop=10)
b=a.reshape(3,3)
print("b:\n",b)
print()
print("b[0:2,0:2]:\n",b[0:2,0:2])
print("shape:",b[0:2,0:2].shape)
print()
print(b[0],"shape:")
print(b[0].shape)
print()
c=b[[0,1],2]
print(c)
print(c.tolist())

b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

b[0:2,0:2]:
 [[1 2]
 [4 5]]
shape: (2, 2)

[1 2 3] shape:
(3,)

[3 6]
[3, 6]


In [72]:
a=np.arange(start=1, stop=10)
b=a[a>5]
c=a[a==1]
d=np.array([False,False,True,True,True,False,False,False,False])
e=a[d]
f=np.array([2,3,4])
g=a[f]
print(b)
print(a>5)
print(c)
print(a==1)
print(d)
print(e)
print(f)
print(g)

[6 7 8 9]
[False False False False False  True  True  True  True]
[1]
[ True False False False False False False False False]
[False False  True  True  True False False False False]
[3 4 5]
[2 3 4]
[3 4 5]


In [88]:
a=np.array([3,1,9,5])
print("원본행렬:", a)
b=np.sort(a)
print("np.sort() 호출 후 반환된 정렬 행렬:",b)
print("np.sort() 호출 후 원본 행렬:",a)
print()
c=a.sort()
print("a.sort() 호출 후 반환된 행렬:",c)
print("a.sort() 호출 후 원본 행렬:",a)
c=a
print("c=a 지정 후 반환된 행렬:",c)
d=np.sort(a)[::-1]
print("슬라이싱[::-1]으로 행렬 뒤집기(내림차순 정렬):",d)

원본행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]

a.sort() 호출 후 반환된 행렬: None
a.sort() 호출 후 원본 행렬: [1 3 5 9]
c=a 지정 후 반환된 행렬: [1 3 5 9]
슬라이싱[::-1]으로 행렬 뒤집기(내림차순 정렬): [9 5 3 1]


In [122]:
a=np.array([[20,5,100],[2,50,600],[1,30,200]])
print("원본행렬:\n",a)
b=np.sort(a,axis=0)
c=np.sort(a,axis=1)
print("로우(행)방향으로 정렬:\n",b)
print("컬럼(열)방향으로 정렬:\n",c)

원본행렬:
 [[ 20   5 100]
 [  2  50 600]
 [  1  30 200]]
로우(행)방향으로 정렬:
 [[  1   5 100]
 [  2  30 200]
 [ 20  50 600]]
컬럼(열)방향으로 정렬:
 [[  5  20 100]
 [  2  50 600]
 [  1  30 200]]


In [124]:
a=np.array([3,1,9,5])
b=np.argsort(a)
c=np.argsort(a)[::-1]
print("행렬 오름차순 정렬 시 원본 행렬의 인덱스:",b)
print("행렬 내림차순 정렬 시 원본 행렬의 인덱스:",c)


행렬 오름차순 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [126]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8],[9,10],[11,12]])
c=np.dot(a,b)
print("행렬 내적 결과:\n",c)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [127]:
a=np.array([[1,2],[3,4]])
b=np.transpose(a)
print("원본 행렬:\n",a)
print("전치 행렬:\n",b)

원본 행렬:
 [[1 2]
 [3 4]]
전치 행렬:
 [[1 3]
 [2 4]]
